### ISSUE TITLE
[IMPROVEMENT] Split Piano King contract in two

### ISSUE THREAD

**Issue by madztheo** [PianoKing-NFT/Smart-Contract#5]
**Description**
Piano King contract is a rather heavy contract in compiled code and is actually pretty close to the contract size limit of 24KB set by the EIP-170. Beyond that size, contracts cannot be deployed as they will be rejected. 

To reduce the size, clean things up a bit, and divide some features, splitting the contract in two would be a nice solution. Piano King will remain the ERC721 contract and keep all its basic features. While the second contract could manage the batch mints by interacting with the Piano King contract.

**Comment by Crunchyman-ralph** [comment]
Are the functionalities of both contracts already done and we just have to split them (refactor them) or does the second contract functionality need to be written?

**Comment by madztheo** [comment]
> Are the functionalities of both contracts already done and we just have to split them (refactor them) or does the second contract functionality need to be written?

It's only about splitting the current features of the Piano King contracts into two distinct ones that cooperate with each other. So there's no need to add any supplementary features, mostly refactorization then.

**Comment by Crunchyman-ralph** [comment]
I read here that it is super expensive to make 2 contracts speak to each other, maybe we can think of 2 contracts that are completely separate from one another.

Ref: https://forum.soliditylang.org/t/mechanism-to-split-large-contracts/91/2

**Comment by madztheo** [comment]
You raise a good point, even if each external call is just a couple of thousand gas it will get magnified by them being called multiple times in the batch mint functions in order to speak with Piano King contract to mint each NFT. 

However, the solution of having the contract split into parts that do not speak to each other requires the use of Proxies or the Diamond Pattern which are rather advanced techniques leveraging DELEGATECALL to call other contracts with the context of the calling contract. This can introduce security risks if not handled properly.

**Comment by Crunchyman-ralph** [comment]
Couldn't we run them independantly ? Are they dependent on each other ?

**Comment by madztheo** [comment]
Most features are dependent yes. Minting requires direct access to Piano King contract storage to update the state of ownership and balance of addresses. Variable setters are for variables necessary on the contract itself.

I think we could maybe move the logic to request and receive the random number to another contract which will forward the number to Piano King contract on reception (so just that one interaction).

getTokenIdInRange and generateTokenId could be moved to a library as well since they are pure functions, although it will not change the size of the contract I believe.
